{% set name = "dask-xgboost" %}
{% set version = "0.2.0.dev28" %}
{% set cuda_version = environ.get('CUDA', '9.2') %}
{% set py_version=environ.get('CONDA_PY', '36') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/dask-xgboost
  git_tag: dask-cudf

build:
  number: 0
  string: cuda{{ cuda_version }}py{{ py_version }}_0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  script_env:
    - CUDA

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - dask >=0.14.0
    - distributed >=1.16.0
    - xgboost
    - cudf
    - dask-cudf
    - cudatoolkit {{ cuda_version }}

about:
  home: http://github.com/dask/dask-xgboost
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Launch, train, and test with XGBoost from Dask'

  description: |
      dask-xgboost is a small project to facilitate launching the XGBoost
      library for machine learning on a Dask cluster.  It also contains
      utilities to transfer data between dask collections like dataframes and
      arrays into a distributed XGBoost system.
  dev_url: https://github.com/dask/dask-xgboost

extra:
  recipe-maintainers:
    - mrocklin
    - TomAugspurger
