name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - conda-python-build
      - conda-python-tests
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@cuda-118
  conda-python-build:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-build.yaml@cuda-118
    with:
      build_type: pull-request
  conda-python-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@cuda-118
    with:
      build_type: pull-request
